name: Coverage
on:
  push:
    branches:
      - master
      - coverage
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: apt update
      run: sudo apt-get update
    - uses: actions/checkout@v2
    - name: Setup requirements
      run: make setup-dev-environment
    - name: Initial setup
      run: ./manage.py initialsetup
    - name: Run tests with coverage
      run: make coverage-run
    - name: Generate coverage report
      run: coverage report
